import { EditorConfig } from "ckeditor5";

export const toolbar: EditorConfig["toolbar"] = {
  items: [
    "undo",
    "redo",
    "|",
    "sourceEditing",
    "showBlocks",
    "findAndReplace",
    "textPartLanguage",
    "fullscreen",
    "|",
    "heading",
    "style",
    "|",
    "fontSize",
    "fontFamily",
    "fontColor",
    "fontBackgroundColor",
    "|",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "subscript",
    "superscript",
    "code",
    "removeFormat",
    "|",
    "emoji",
    "specialCharacters",
    "horizontalLine",
    "pageBreak",
    "link",
    "insertImage",
    "mediaEmbed",
    "insertTable",
    "insertTableLayout",
    "highlight",
    "blockQuote",
    "codeBlock",
    "htmlEmbed",
    "|",
    "alignment",
    "|",
    "bulletedList",
    "numberedList",
    "todoList",
    "outdent",
    "indent",
  ],
  shouldNotGroupWhenFull: true,
};
